function loadDepositForm(ffid,cuid,fiLabel,cuLabel){$("#hiddenFiId").val(ffid);$("#hiddenCuId").val(cuid);$("#hiddenFiLabel").val(fiLabel);$("#hiddenCuLabel").val(cuLabel);}
$(document).ready(function(){$('.fi-tile').on('click',function(){$fi=$(this);var ffid=$fi.attr('fiid')=="undefined"?"":$fi.attr('fiid');var cuid=$fi.attr('cuid')=="undefined"?"":$fi.attr('cuid');var fiLabel=(ffid=="")?"":$fi.attr('fiLabel');var cuLabel=(cuid=="")?"":$fi.attr('fiLabel');loadDepositForm(ffid,cuid,fiLabel,cuLabel);depositFireGA("logo");var timeOutEnabled=$("#manualDelay").size()==0?0:$("#manualDelay").val();var endTimeinMs=new Date().getTime();timeOutEnabled=getCorrectedDelay(endTimeinMs,timeOutEnabled);if(parseInt(timeOutEnabled)>0){displaySpinner();setTimeout(function(){submitForm();},parseInt(timeOutEnabled));}else{submitForm();}});});$(document).ready(function(){$("#selectFiId").change(function(){$('[id^="selectCu-"]').hide();$("#provinceAccessoryCheckmark").hide();$("#provinceAccessoryCheckmark").attr("aria-checked",false);$("#cuAccessoryCheckmark").hide();$("#cuAccessoryCheckmark").attr("aria-checked",false);$("#province").val($("#province option:first").val());$("#placeholderCU").show();var cuidValue=$("option:selected",this).attr("cuid");$("#hiddenCuId").val(cuidValue);var fiLabel=$("option:selected",this).attr("fiLabel");$("#hiddenCuLabel").val("");$("#hiddenFiLabel").val(fiLabel);var option=$("option:selected",this).val();$("#hiddenFiId").val(option);if(option!=""){$(".fi-select-submit").removeAttr('disabled');$("#fiAccessoryCheckmark").show();$("#fiAccessoryCheckmark").attr("aria-checked",true);}else{$(".fi-select-submit").attr('disabled','disabled');$("#fiAccessoryCheckmark").hide();$("#fiAccessoryCheckmark").attr("aria-checked",false);}});$("#province").change(function(){$("#selectFiId").val($("#selectFiId option:first").val());$("#fiAccessoryCheckmark").hide();$("#cuAccessoryCheckmark").hide();$("#cuAccessoryCheckmark").attr("aria-checked",false);$("#fiAccessoryCheckmark").attr("aria-checked",false);var selectedProvinceCode=$("option:selected",this).val();$("#placeholderCU").hide();$("#provinceAccessoryCheckmark").show();$("#provinceAccessoryCheckmark").attr("aria-checked",true);$(".selectCu").each(function(){if($(this).attr("provinceCode")){if($(this).attr("provinceCode")===selectedProvinceCode){$(this).show();}else{$(this).hide();}}
$("option",this).each(function(){if($(this).attr("value")!==""){$(this).prop("selected",false);}else{$(this).prop("selected",true);}});});if(selectedProvinceCode!==""){$("#selectCu-"+selectedProvinceCode).show();$("#selectCu-hintlabel-"+selectedProvinceCode).show();$("#selectCu-title-"+selectedProvinceCode).show();$("#selectCu-"+selectedProvinceCode).val($("#selectCu-"+selectedProvinceCode).val());}else{$("#placeholderCU").show();$("#provinceAccessoryCheckmark").hide();$("#provinceAccessoryCheckmark").attr("aria-checked",false);}
$(".cu-select-submit").attr('disabled','disabled');});$("#selectCu-SK").change(function(){var fiIdValue=$("option:selected",this).attr("fiid");$("#hiddenFiId").val(fiIdValue);var option=$("option:selected",this).val();$("#hiddenCuId").val(option);if(option!=""){$(".cu-select-submit").removeAttr('disabled');$("#cuAccessoryCheckmark").show();$("#cuAccessoryCheckmark").attr("aria-checked",true);}else{$(".cu-select-submit").attr('disabled','disabled');$("#cuAccessoryCheckmark").hide();$("#cuAccessoryCheckmark").attr("aria-checked",false);}
var fiIdName=$("option:selected",this).attr("fiLabel");$("#hiddenCuLabel").val(fiIdName);$("#hiddenFiLabel").val("");});$("#selectCu-AB").change(function(){var fiIdValue=$("option:selected",this).attr("fiid");$("#hiddenFiId").val(fiIdValue);var option=$("option:selected",this).val();$("#hiddenCuId").val(option);if(option!=""){$(".cu-select-submit").removeAttr('disabled');$("#cuAccessoryCheckmark").show();$("#cuAccessoryCheckmark").attr("aria-checked",true);}else{$(".cu-select-submit").attr('disabled','disabled');$("#cuAccessoryCheckmark").hide();$("#cuAccessoryCheckmark").attr("aria-checked",false);}
var fiIdName=$("option:selected",this).attr("fiLabel");$("#hiddenCuLabel").val(fiIdName);$("#hiddenFiLabel").val("");});$("#selectCu-BC").change(function(){var fiIdValue=$("option:selected",this).attr("fiid");$("#hiddenFiId").val(fiIdValue);var option=$("option:selected",this).val();$("#hiddenCuId").val(option);if(option!=""){$(".cu-select-submit").removeAttr('disabled');$("#cuAccessoryCheckmark").show();$("#cuAccessoryCheckmark").attr("aria-checked",true);}else{$(".cu-select-submit").attr('disabled','disabled');$("#cuAccessoryCheckmark").hide();$("#cuAccessoryCheckmark").attr("aria-checked",false);}
var fiIdName=$("option:selected",this).attr("fiLabel");$("#hiddenCuLabel").val(fiIdName);$("#hiddenFiLabel").val("");});$("#selectCu-MB").change(function(){var fiIdValue=$("option:selected",this).attr("fiid");$("#hiddenFiId").val(fiIdValue);var option=$("option:selected",this).val();$("#hiddenCuId").val(option);if(option!=""){$(".cu-select-submit").removeAttr('disabled');$("#cuAccessoryCheckmark").show();$("#cuAccessoryCheckmark").attr("aria-checked",true);}else{$(".cu-select-submit").attr('disabled','disabled');$("#cuAccessoryCheckmark").hide();$("#cuAccessoryCheckmark").attr("aria-checked",false);}
var fiIdName=$("option:selected",this).attr("fiLabel");$("#hiddenCuLabel").val(fiIdName);$("#hiddenFiLabel").val("");});$("#selectCu-NB").change(function(){var fiIdValue=$("option:selected",this).attr("fiid");$("#hiddenFiId").val(fiIdValue);var option=$("option:selected",this).val();$("#hiddenCuId").val(option);if(option!=""){$(".cu-select-submit").removeAttr('disabled');$("#cuAccessoryCheckmark").show();$("#cuAccessoryCheckmark").attr("aria-checked",true);}else{$(".cu-select-submit").attr('disabled','disabled');$("#cuAccessoryCheckmark").hide();$("#cuAccessoryCheckmark").attr("aria-checked",false);}
var fiIdName=$("option:selected",this).attr("fiLabel");$("#hiddenCuLabel").val(fiIdName);$("#hiddenFiLabel").val("");});$("#selectCu-NL").change(function(){var fiIdValue=$("option:selected",this).attr("fiid");$("#hiddenFiId").val(fiIdValue);var option=$("option:selected",this).val();$("#hiddenCuId").val(option);if(option!=""){$(".cu-select-submit").removeAttr('disabled');$("#cuAccessoryCheckmark").show();$("#cuAccessoryCheckmark").attr("aria-checked",true);}else{$(".cu-select-submit").attr('disabled','disabled');$("#cuAccessoryCheckmark").hide();$("#cuAccessoryCheckmark").attr("aria-checked",false);}
var fiIdName=$("option:selected",this).attr("fiLabel");$("#hiddenCuLabel").val(fiIdName);$("#hiddenFiLabel").val("");});$("#selectCu-NT").change(function(){var fiIdValue=$("option:selected",this).attr("fiid");$("#hiddenFiId").val(fiIdValue);var option=$("option:selected",this).val();$("#hiddenCuId").val(option);if(option!=""){$(".cu-select-submit").removeAttr('disabled');$("#cuAccessoryCheckmark").show();$("#cuAccessoryCheckmark").attr("aria-checked",true);}else{$(".cu-select-submit")
$(".cu-select-submit").attr('disabled','disabled');$("#cuAccessoryCheckmark").hide();$("#cuAccessoryCheckmark").attr("aria-checked",false);}
var fiIdName=$("option:selected",this).attr("fiLabel");$("#hiddenCuLabel").val(fiIdName);$("#hiddenFiLabel").val("");});$("#selectCu-NS").change(function(){var fiIdValue=$("option:selected",this).attr("fiid");$("#hiddenFiId").val(fiIdValue);var option=$("option:selected",this).val();$("#hiddenCuId").val(option);if(option!=""){$(".cu-select-submit").removeAttr('disabled');$("#cuAccessoryCheckmark").show();$("#cuAccessoryCheckmark").attr("aria-checked",true);}else{$(".cu-select-submit")
$(".cu-select-submit").attr('disabled','disabled');$("#cuAccessoryCheckmark").hide();$("#cuAccessoryCheckmark").attr("aria-checked",false);}
var fiIdName=$("option:selected",this).attr("fiLabel");$("#hiddenCuLabel").val(fiIdName);$("#hiddenFiLabel").val("");});$("#selectCu-NU").change(function(){var fiIdValue=$("option:selected",this).attr("fiid");$("#hiddenFiId").val(fiIdValue);var option=$("option:selected",this).val();$("#hiddenCuId").val(option);if(option!=""){$(".cu-select-submit").removeAttr('disabled');$("#cuAccessoryCheckmark").show();$("#cuAccessoryCheckmark").attr("aria-checked",true);}else{$(".cu-select-submit")
$(".cu-select-submit").attr('disabled','disabled');$("#cuAccessoryCheckmark").hide();$("#cuAccessoryCheckmark").attr("aria-checked",false);}
var fiIdName=$("option:selected",this).attr("fiLabel");$("#hiddenCuLabel").val(fiIdName);$("#hiddenFiLabel").val("");});$("#selectCu-ON").change(function(){var fiIdValue=$("option:selected",this).attr("fiid");$("#hiddenFiId").val(fiIdValue);var option=$("option:selected",this).val();$("#hiddenCuId").val(option);if(option!=""){$(".cu-select-submit").removeAttr('disabled');$("#cuAccessoryCheckmark").show();$("#cuAccessoryCheckmark").attr("aria-checked",true);}else{$(".cu-select-submit")
$(".cu-select-submit").attr('disabled','disabled');$("#cuAccessoryCheckmark").hide();$("#cuAccessoryCheckmark").attr("aria-checked",false);}
var fiIdName=$("option:selected",this).attr("fiLabel");$("#hiddenCuLabel").val(fiIdName);$("#hiddenFiLabel").val("");});$("#selectCu-PE").change(function(){var fiIdValue=$("option:selected",this).attr("fiid");$("#hiddenFiId").val(fiIdValue);var option=$("option:selected",this).val();$("#hiddenCuId").val(option);if(option!=""){$(".cu-select-submit").removeAttr('disabled');$("#cuAccessoryCheckmark").show();$("#cuAccessoryCheckmark").attr("aria-checked",true);}else{$(".cu-select-submit")
$(".cu-select-submit").attr('disabled','disabled');$("#cuAccessoryCheckmark").hide();$("#cuAccessoryCheckmark").attr("aria-checked",false);}
var fiIdName=$("option:selected",this).attr("fiLabel");$("#hiddenCuLabel").val(fiIdName);$("#hiddenFiLabel").val("");});$("#selectCu-QC").change(function(){var fiIdValue=$("option:selected",this).attr("fiid");$("#hiddenFiId").val(fiIdValue);var option=$("option:selected",this).val();$("#hiddenCuId").val(option);if(option!=""){$(".cu-select-submit").removeAttr('disabled');$("#cuAccessoryCheckmark").show();$("#cuAccessoryCheckmark").attr("aria-checked",true);}else{$(".cu-select-submit")
$(".cu-select-submit").attr('disabled','disabled');$("#cuAccessoryCheckmark").hide();$("#cuAccessoryCheckmark").attr("aria-checked",false);}
var fiIdName=$("option:selected",this).attr("fiLabel");$("#hiddenCuLabel").val(fiIdName);$("#hiddenFiLabel").val("");});$("#selectCu-YT").change(function(){var fiIdValue=$("option:selected",this).attr("fiid");$("#hiddenFiId").val(fiIdValue);var option=$("option:selected",this).val();$("#hiddenCuId").val(option);if(option!=""){$(".cu-select-submit").removeAttr('disabled');$("#cuAccessoryCheckmark").show();$("#cuAccessoryCheckmark").attr("aria-checked",true);}else{$(".cu-select-submit")
$(".cu-select-submit").attr('disabled','disabled');$("#cuAccessoryCheckmark").hide();$("#cuAccessoryCheckmark").attr("aria-checked",false);}
var fiIdName=$("option:selected",this).attr("fiLabel");$("#hiddenCuLabel").val(fiIdName);$("#hiddenFiLabel").val("");});});$(document).ready(function(){$("form").submit(function(event){return true;});$('.fi-select-submit').click(function(){depositFireGA("dropdown");});$('.search-submit').click(function(){depositFireGA("search");});});function depositFireGA(mode){if(document.getElementById("depositForm")){var sessionPaymentRef=$("#paymentRefNum").val();var amount=0;if($("#fmtAmount").length){fmt=$("#fmtAmount").val();var amountString=fmt.substring(1,fmt.length);if($("#language").val()=="fr"){amountString=fmt.substring(0,fmt.length-1);}
var amount=parseFloat(amountString);}
var fiCuIdvalue=$("#hiddenFiId").val();if($("#hiddenCuId").val()!=""){fiCuIdvalue=$("#hiddenCuId").val();}
var fiCuLabel=$("#hiddenFiLabel").val();if(mode=="dropdown"||mode!=="search"){if($("#hiddenFiLabel").val()!=""){fireFiDepositGA(sessionPaymentRef,amount,fiCuIdvalue,mode);}else if($("#hiddenCuLabel").val()!=""){fiCuLabel=$("#hiddenCuLabel").val();fireCuDepositGA(sessionPaymentRef,amountString,fiCuIdvalue,mode);}}
if($("#fmtAmount").length){dataLayer.push({'event':'transactionComplete','transactionId':sessionPaymentRef,'transactionAffiliation':'eTransfer','transactionTotal':amount,'transactionProducts':[{'sku':fiCuIdvalue,'name':fiCuLabel,'price':amount,'quantity':1}]});}}}
function fireFiDepositGA(sessionPaymentRef,amount,fiIdvalue,mode){var hiddenFiLabel=$("#hiddenFiLabel").val();dataLayer.push({'event':'GAEvent','eventCategory':'Deposit','eventAction':'Financial Institution','depositMethod':mode,'eventLabel':hiddenFiLabel,'transactionId':sessionPaymentRef,'transactionAffiliation':'eTransfer','transactionTotal':amount,'transactionProducts':[{'sku':fiIdvalue,'name':hiddenFiLabel,'price':amount,'quantity':1}]});}
function fireCuDepositGA(sessionPaymentRef,amount,fiIdvalue,mode){var hiddenCuLabel=$("#hiddenCuLabel").val();dataLayer.push({'event':'GAEvent','eventCategory':'Deposit','eventAction':'Credit Union','depositMethod':mode,'eventLabel':hiddenCuLabel,'transactionId':sessionPaymentRef,'transactionAffiliation':'eTransfer','transactionTotal':amount,'transactionProducts':[{'sku':fiIdvalue,'name':hiddenCuLabel,'price':amount,'quantity':1}]});}
var optionHasBeenSelected=false;var searchIsopened=false;var autocompleteScrolled=false;var initial_screen_size=window.innerHeight;var dragging=false;$(document).ready(function(){var optionsListSize=8;var maxResults=5;if(mobilecheck()||(Modernizr.touch&&Modernizr.mq('only all and (max-width: 567px)'))){optionsListSize=3;maxResults=3;var ua=navigator.userAgent.toLowerCase();var isAndroid=ua.indexOf("android")>-1;var isIphone=ua.indexOf("iphone")>-1;window.addEventListener("orientationchange",function(){var is_keyboard=(window.innerHeight<initial_screen_size);if(Math.abs(window.orientation)===90){if(searchIsopened){closeSearch();}
if(isAndroid){$("#search-container").hide();}}else{if(isAndroid){$("#search-container").show();}}},false);if(isAndroid){var mql=window.matchMedia("(orientation: portrait)");if(mql.matches){$("#search-container").show();}else{$("#search-container").hide();}}
if(!isIphone){$("#autocomplete-typehead-div").css("padding-left","3% !important");}
$(window).scroll(function(){var searchPosition=$("#search-pos").offset().top;if($(this).scrollTop()>searchPosition){enableSearchFloating();}else{disableSearchFloating();}});}
$("#autocomplete-input").on('touchend change textInput input',function(e){if(mobilecheck()||(Modernizr.touch&&Modernizr.mq('only all and (max-width: 567px)'))){var searchPosition=$("#autocomplete-input").offset().top;if(searchPosition<400){$('html, body').animate({scrollTop:searchPosition},'slow');}
autocompleteScrolled=true;}
$('.refine-search-panel').hide("fade");});$("body").on("touchmove",function(){dragging=true;});$("body").on("touchstart",function(){dragging=false;});var fiListOption=$("#fiListOption").val();var allFisCus=new Bloodhound({datumTokenizer:function(data){if($("#language").val()=="en"){return Bloodhound.tokenizers.whitespace(data.languageDependentFiCuName.en);}else{return Bloodhound.tokenizers.whitespace(data.languageDependentFiCuName.fr);}},queryTokenizer:Bloodhound.tokenizers.whitespace,prefetch:'/getAllFisandCus.do?lang='+$("#language").val()+'&fiListOption='+fiListOption});$('#autocomplete-input').typeahead({hint:false,highlight:false,accent:true},{displayKey:function(suggestion){if($("#language").val()=="en"){return suggestion.languageDependentFiCuName.en;}else{return suggestion.languageDependentFiCuName.fr;}},name:'allFisCus',source:allFisCus,limit:optionsListSize,templates:{empty:$("#no-results-panel").html(),footer:$("#autocomplete_div").html()}}).on("typeahead:selected",function(obj,responseData){doFiSelection(responseData);}).on("typeahead:render",function(){var optionsLength=$(".tt-selectable").length;$(".tt-menu").attr("role","listbox");$(".tt-menu").attr("aria-labelledby","sb-search");$(".tt-suggestion").attr("role","option");$(".tt-suggestion").attr("aria-selected","false");$("#autocomplete-input").attr("aria-expanded","true");if(optionsLength>=maxResults){$('.refine-search-panel').show("fade");}else{$('.refine-search-panel').hide("fade");}}).on("typeahead:close",function(){$("#autocomplete-input").attr("aria-expanded","false");});$(document).keyup(function(e){if(e.keyCode==27&&searchIsopened){closeSearch();}});});function prepareSearchPanel(){autocompleteScrolled=false;var autocomplete=$('#autocomplete-input');var oldSearchTypeAheadValue=autocomplete.typeahead('val');if(oldSearchTypeAheadValue.length>0){autocomplete.typeahead('val','');autocomplete.val(oldSearchTypeAheadValue);}
$('a.ui-input-clear,#clearSearch').click(function(){clearSearchFunc();});}
function showSelectedFiDetails(fiLabel){hideFiLogos();showSearchZone();$("#selectedFiValue").html(fiLabel);$("#fiDetailPanel").attr("class","pure-u-1 deposit-form-submit-btn search-submit");}
function clearSearchFunc(){var autocompleteInput=$('#autocomplete-input');autocompleteInput.typeahead('val','');$("#close-icon").attr("class","");$('input#autocomplete-input').val('');optionHasBeenSelected=false;$('.refine-search-panel').hide("fade");loadDepositForm('','','','','');$("#fiDetailPanel").attr("class","pure-u-1 deposit-form-submit-btn search-submit visibility-hidden");$(".deposit-form-submit-btn").prop("disabled",true);};(function(window){'use strict';!window.addEventListener&&window.Element&&(function(){function addToPrototype(name,method){Window.prototype[name]=HTMLDocument.prototype[name]=Element.prototype[name]=method;}
var registry=[];addToPrototype("addEventListener",function(type,listener){var target=this;registry.unshift({__listener:function(event){event.currentTarget=target;event.pageX=event.clientX+document.documentElement.scrollLeft;event.pageY=event.clientY+document.documentElement.scrollTop;event.preventDefault=function(){event.returnValue=false};event.relatedTarget=event.fromElement||null;event.stopPropagation=function(){event.cancelBubble=true};event.relatedTarget=event.fromElement||null;event.target=event.srcElement||target;event.timeStamp=+new Date;listener.call(target,event);},listener:listener,target:target,type:type});this.attachEvent("on"+type,registry[0].__listener);});addToPrototype("removeEventListener",function(type,listener){for(var index=0,length=registry.length;index<length;++index){if(registry[index].target==this&&registry[index].type==type&&registry[index].listener==listener){return this.detachEvent("on"+type,registry.splice(index,1)[0].__listener);}}});addToPrototype("dispatchEvent",function(eventObject){try{return this.fireEvent("on"+eventObject.type,eventObject);}catch(error){for(var index=0,length=registry.length;index<length;++index){if(registry[index].target==this&&registry[index].type==eventObject.type){registry[index].call(this,eventObject);}}}});})();!String.prototype.trim&&(String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,'');});function UISearch(el,options){this.el=el;this._initEvents();}
UISearch.prototype={_initEvents:function(){var self=this,initSearchFn=function(ev){if(dragging){dragging=false;return false;}
ev.stopPropagation();if($("#sb-search").hasClass("sb-search-close")){ev.preventDefault();self.open();}
else if($("#sb-search").hasClass("sb-search-open")){ev.preventDefault();self.close();}};this.el.addEventListener('click',initSearchFn);this.el.addEventListener('touchend',initSearchFn);},open:function(){openSearch()},close:function(){closeSearch()}}
window.UISearch=UISearch;})(window);function mobilecheck(){var check=false;(function(a){if(/(android|ipad|playbook|silk|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|yas\-|your|zeto|zte\-/i.test(a.substr(0,4)))check=true})(navigator.userAgent||navigator.vendor||window.opera);return check;}
function openSearch(){if(mobilecheck()||(Modernizr.touch&&Modernizr.mq('only all and (max-width: 567px)'))){scrollToSearch();}
setTimeout(function(){activateSearch();disableFiLogosClick();prepareSearchPanel();searchIsopened=true;},200);}
function closeSearch(){deactivateSearch();clearSearchFunc();hideSearchZone();showFiLogos();enableFiLogosClick();searchIsopened=false;$("#autocomplete-input").blur();$("#sb-search").focus();}
function activateSearch(){$("#sb-search").addClass('sb-search-open').addClass('typeahead').removeClass('sb-search-close').attr("aria-pressed","true");var closeIcon=document.querySelector('#close-icon');closeIcon.setAttribute("style","");$("#select-fi-title").removeClass("title-on").addClass("title-off");$("#search-title").removeClass("title-off").addClass("title-on",150);$("#search-icon").attr("class","visibility-hidden").attr("aria-hidden","true");$("#close-icon").attr("aria-hidden","false");$("#search-retracted-label").addClass("visibility-hidden");setTimeout(function(){$("#autocomplete-input").removeClass("visibility-hidden");setTimeout(function(){$("#autocomplete-input").focus();},130);},500);var bodyFn=function(ev){this.removeEventListener('click',bodyFn);this.removeEventListener('touchend',bodyFn);};document.addEventListener('click',bodyFn);document.addEventListener('touchend',bodyFn);}
function deactivateSearch(){var closeIcon=document.querySelector('#close-icon');closeIcon.setAttribute("style","visibility:hidden");$("#autocomplete-input").addClass("visibility-hidden",10);$("#search-icon").attr("class","yellow-background circle-icon").attr("aria-hidden","false");$("#close-icon").attr("aria-hidden","true");$("#search-retracted-label").removeClass("visibility-hidden");$("#sb-search").removeClass('sb-search-open').addClass('sb-search-close').removeClass('typeahead').attr("aria-pressed","false").blur();$("#search-title").removeClass("title-on").addClass("title-off");$("#select-fi-title").removeClass("title-off").addClass("title-on",150);}
function showFiLogos(){setTimeout(function(){$("#fiOptionsPane").removeClass("visibility-hidden",10);},200);}
function hideFiLogos(){$("#fiOptionsPane").addClass("visibility-hidden",100);}
function enableFiLogosClick(){$("#fiOptionsPane").removeClass("disabled-panel");$("#fiOptionsdisabled").hide("fade");}
function disableFiLogosClick(){$("#fiOptionsPane").addClass("disabled-panel",100);$("#fiOptionsdisabled").show("fade");}
function showSearchZone(){setTimeout(function(){$("#searchPane").removeClass("visibility-hidden",10);},200);}
function hideSearchZone(){$("#searchPane").addClass("visibility-hidden",100).css({position:'absolute'});}
function enableSearchFloating(){$("#search-container").addClass('search-container-floating');$("#sb-search").addClass('sb-search-floating');$("#search-wrapper").addClass('padding-right-15');}
function disableSearchFloating(){if($("#search-container").hasClass('search-container-floating')){$("#search-container").removeClass('search-container-floating');}
if($("#sb-search").hasClass('sb-search-floating')){$("#sb-search").removeClass('sb-search-floating');}
if($("#search-wrapper").hasClass('padding-right-15')){$("#search-wrapper").removeClass('padding-right-15');}}
function doFiSelection(responseData){var labelValue="";var fiid=responseData.fiId;var cuid=responseData.creditUnionId;if(cuid=="undefined"||cuid=="null"){cuid="";}
if($("#language").val()=="en"){labelValue=responseData.languageDependentFiCuName.en;}else{labelValue=responseData.languageDependentFiCuName.fr;}
var fiLabel=labelValue;var cuLabel=(cuid=="")?"":labelValue;$("#depositSearchSubmit").prop("disabled",false);optionHasBeenSelected=true;enableFiLogosClick();loadDepositForm(fiid,cuid,fiLabel,cuLabel);setTimeout(function(){showSelectedFiDetails(labelValue);},200);}
function scrollToSearch(){var searchPosition=$("#search-pos").offset().top;if($(this).scrollTop()>searchPosition){disableSearchFloating();}
setTimeout(function(){$('html, body').animate({scrollTop:searchPosition},'slow');},200);}
new UISearch(document.getElementById('sb-search'));